### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by ghost** [x-punch/gin-prometheus#1]
Hi @xpunch ,

Hope you are all well !

Sorry to bother you, but I am looking for a gin middleware for exporting gin statistics to prometheus. 
So I found your repository :-)

I tried your middleware but it doesn't forward metrics to prometheus ? (btw I dockerized grafana and all others services)

Thanks for any insights or clarifications on how to push data into prometheus.

Cheers,
Luc Michalski

**Comment by xpunch** [comment]
Do you try my example?
After you integrate this middleware, you should be able to access /metrics through GET request.
Then your prometheus will be able to pull data from your service.
There is no way to push data into prometheus, the only way is use prometheus-pushgateway, which is not recommended for new system.

**Comment by ghost** [comment]
Sorry, I made it work my prometheus.yml file was not properly configured ^^

Thanks for the middleware :-)

**Comment by ghost** [comment]
Btw, I have another question. ^^

How would you forward data from this other middleware github.com/cjgiridhar/gin-geo to prometheus ?

**Comment by xpunch** [comment]
I don't understand your question, if you want to add new metrics to forward external information, you need to design your own metrics.
As you can see, my middleware only supports metrics for basic running status of service.

**Comment by ghost** [comment]
Hi @xpunch ,

I solved my issue by using the following project and posted more details on my use case : https://github.com/penglongli/gin-metrics/issues/2.

Anyway, thanks for your repository :-)

Have a nice day !
